services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    expose:
      - "9000"
    depends_on:
      - db
    networks:
      - main

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
      - /etc/ssl/lakovrv:/etc/ssl/lakovrv
    depends_on:
      - app
    networks:
      - main

  db:
    image: postgres
    env_file: .env
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - main

volumes:
  postgres:

networks:
  main:
    driver: bridge
